export const images: Record<string, string> = {
  openclaw: "ghcr.io/pocketenv-io/modal-openclaw:0.1.0",
  amp: "ghcr.io/pocketenv-io/modal-amp:0.1.0",
  claude: "ghcr.io/pocketenv-io/modal-claude:0.1.0",
  codex: "ghcr.io/pocketenv-io/modal-codex:0.1.0",
  copilot: "ghcr.io/pocketenv-io/modal-copilot:0.1.0",
  crush: "ghcr.io/pocketenv-io/modal-crush:0.1.0",
  cursor: "ghcr.io/pocketenv-io/modal-cursor:0.1.0",
  gemini: "ghcr.io/pocketenv-io/modal-gemini:0.1.0",
  kilo: "ghcr.io/pocketenv-io/modal-kilo:0.1.0",
  kiro: "ghcr.io/pocketenv-io/modal-kiro:0.1.0",
  mise: "ghcr.io/pocketenv-io/modal-mise:0.1.0",
  nix: "ghcr.io/pocketenv-io/modal-nix:0.1.0",
  nullclaw: "ghcr.io/pocketenv-io/modal-nullclaw:0.1.0",
  opencode: "ghcr.io/pocketenv-io/modal-opencode:0.1.0",
  opencrust: "ghcr.io/pocketenv-io/modal-opencrust:0.1.0",
  picoclaw: "ghcr.io/pocketenv-io/modal-picoclaw:0.1.0",
  pkgx: "ghcr.io/pocketenv-io/modal-pkgx:0.1.0",
  wasmer: "ghcr.io/pocketenv-io/modal-wasmer:0.1.0",
  zeroclaw: "ghcr.io/pocketenv-io/modal-zeroclaw:0.1.0",
};
