/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolumesRouteImport } from './routes/volumes'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SandboxIdRouteImport } from './routes/sandbox/$id'
import { Route as DidSandboxRkeyRouteImport } from './routes/$did.sandbox.$rkey'
import { Route as DidSandboxRkeyIndexRouteImport } from './routes/$did.sandbox.$rkey/index'
import { Route as DidSandboxRkeyVolumesRouteImport } from './routes/$did.sandbox.$rkey/volumes'
import { Route as DidSandboxRkeyVariablesRouteImport } from './routes/$did.sandbox.$rkey/variables'
import { Route as DidSandboxRkeyTailscaleRouteImport } from './routes/$did.sandbox.$rkey/tailscale'
import { Route as DidSandboxRkeySshKeysRouteImport } from './routes/$did.sandbox.$rkey/ssh-keys'
import { Route as DidSandboxRkeySettingsRouteImport } from './routes/$did.sandbox.$rkey/settings'
import { Route as DidSandboxRkeyServicesRouteImport } from './routes/$did.sandbox.$rkey/services'
import { Route as DidSandboxRkeySecretsRouteImport } from './routes/$did.sandbox.$rkey/secrets'
import { Route as DidSandboxRkeyRepositoryRouteImport } from './routes/$did.sandbox.$rkey/repository'
import { Route as DidSandboxRkeyPortsRouteImport } from './routes/$did.sandbox.$rkey/ports'
import { Route as DidSandboxRkeyIntegrationsRouteImport } from './routes/$did.sandbox.$rkey/integrations'
import { Route as DidSandboxRkeyFilesRouteImport } from './routes/$did.sandbox.$rkey/files'

const VolumesRoute = VolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxIdRoute = SandboxIdRouteImport.update({
  id: '/sandbox/$id',
  path: '/sandbox/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DidSandboxRkeyRoute = DidSandboxRkeyRouteImport.update({
  id: '/$did/sandbox/$rkey',
  path: '/$did/sandbox/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)
const DidSandboxRkeyIndexRoute = DidSandboxRkeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DidSandboxRkeyRoute,
} as any)
const DidSandboxRkeyVolumesRoute = DidSandboxRkeyVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => DidSandboxRkeyRoute,
} as any)
const DidSandboxRkeyVariablesRoute = DidSandboxRkeyVariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => DidSandboxRkeyRoute,
} as any)
const DidSandboxRkeyTailscaleRoute = DidSandboxRkeyTailscaleRouteImport.update({
  id: '/tailscale',
  path: '/tailscale',
  getParentRoute: () => DidSandboxRkeyRoute,
} as any)
const DidSandboxRkeySshKeysRoute = DidSandboxRkeySshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => DidSandboxRkeyRoute,
} as any)
const DidSandboxRkeySettingsRoute = DidSandboxRkeySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DidSandboxRkeyRoute,
} as any)
const DidSandboxRkeyServicesRoute = DidSandboxRkeyServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DidSandboxRkeyRoute,
} as any)
const DidSandboxRkeySecretsRoute = DidSandboxRkeySecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => DidSandboxRkeyRoute,
} as any)
const DidSandboxRkeyRepositoryRoute =
  DidSandboxRkeyRepositoryRouteImport.update({
    id: '/repository',
    path: '/repository',
    getParentRoute: () => DidSandboxRkeyRoute,
  } as any)
const DidSandboxRkeyPortsRoute = DidSandboxRkeyPortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => DidSandboxRkeyRoute,
} as any)
const DidSandboxRkeyIntegrationsRoute =
  DidSandboxRkeyIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => DidSandboxRkeyRoute,
  } as any)
const DidSandboxRkeyFilesRoute = DidSandboxRkeyFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DidSandboxRkeyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/snapshots': typeof SnapshotsRoute
  '/volumes': typeof VolumesRoute
  '/sandbox/$id': typeof SandboxIdRoute
  '/$did/sandbox/$rkey': typeof DidSandboxRkeyRouteWithChildren
  '/$did/sandbox/$rkey/files': typeof DidSandboxRkeyFilesRoute
  '/$did/sandbox/$rkey/integrations': typeof DidSandboxRkeyIntegrationsRoute
  '/$did/sandbox/$rkey/ports': typeof DidSandboxRkeyPortsRoute
  '/$did/sandbox/$rkey/repository': typeof DidSandboxRkeyRepositoryRoute
  '/$did/sandbox/$rkey/secrets': typeof DidSandboxRkeySecretsRoute
  '/$did/sandbox/$rkey/services': typeof DidSandboxRkeyServicesRoute
  '/$did/sandbox/$rkey/settings': typeof DidSandboxRkeySettingsRoute
  '/$did/sandbox/$rkey/ssh-keys': typeof DidSandboxRkeySshKeysRoute
  '/$did/sandbox/$rkey/tailscale': typeof DidSandboxRkeyTailscaleRoute
  '/$did/sandbox/$rkey/variables': typeof DidSandboxRkeyVariablesRoute
  '/$did/sandbox/$rkey/volumes': typeof DidSandboxRkeyVolumesRoute
  '/$did/sandbox/$rkey/': typeof DidSandboxRkeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/snapshots': typeof SnapshotsRoute
  '/volumes': typeof VolumesRoute
  '/sandbox/$id': typeof SandboxIdRoute
  '/$did/sandbox/$rkey/files': typeof DidSandboxRkeyFilesRoute
  '/$did/sandbox/$rkey/integrations': typeof DidSandboxRkeyIntegrationsRoute
  '/$did/sandbox/$rkey/ports': typeof DidSandboxRkeyPortsRoute
  '/$did/sandbox/$rkey/repository': typeof DidSandboxRkeyRepositoryRoute
  '/$did/sandbox/$rkey/secrets': typeof DidSandboxRkeySecretsRoute
  '/$did/sandbox/$rkey/services': typeof DidSandboxRkeyServicesRoute
  '/$did/sandbox/$rkey/settings': typeof DidSandboxRkeySettingsRoute
  '/$did/sandbox/$rkey/ssh-keys': typeof DidSandboxRkeySshKeysRoute
  '/$did/sandbox/$rkey/tailscale': typeof DidSandboxRkeyTailscaleRoute
  '/$did/sandbox/$rkey/variables': typeof DidSandboxRkeyVariablesRoute
  '/$did/sandbox/$rkey/volumes': typeof DidSandboxRkeyVolumesRoute
  '/$did/sandbox/$rkey': typeof DidSandboxRkeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/snapshots': typeof SnapshotsRoute
  '/volumes': typeof VolumesRoute
  '/sandbox/$id': typeof SandboxIdRoute
  '/$did/sandbox/$rkey': typeof DidSandboxRkeyRouteWithChildren
  '/$did/sandbox/$rkey/files': typeof DidSandboxRkeyFilesRoute
  '/$did/sandbox/$rkey/integrations': typeof DidSandboxRkeyIntegrationsRoute
  '/$did/sandbox/$rkey/ports': typeof DidSandboxRkeyPortsRoute
  '/$did/sandbox/$rkey/repository': typeof DidSandboxRkeyRepositoryRoute
  '/$did/sandbox/$rkey/secrets': typeof DidSandboxRkeySecretsRoute
  '/$did/sandbox/$rkey/services': typeof DidSandboxRkeyServicesRoute
  '/$did/sandbox/$rkey/settings': typeof DidSandboxRkeySettingsRoute
  '/$did/sandbox/$rkey/ssh-keys': typeof DidSandboxRkeySshKeysRoute
  '/$did/sandbox/$rkey/tailscale': typeof DidSandboxRkeyTailscaleRoute
  '/$did/sandbox/$rkey/variables': typeof DidSandboxRkeyVariablesRoute
  '/$did/sandbox/$rkey/volumes': typeof DidSandboxRkeyVolumesRoute
  '/$did/sandbox/$rkey/': typeof DidSandboxRkeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/projects'
    | '/secrets'
    | '/settings'
    | '/signin'
    | '/snapshots'
    | '/volumes'
    | '/sandbox/$id'
    | '/$did/sandbox/$rkey'
    | '/$did/sandbox/$rkey/files'
    | '/$did/sandbox/$rkey/integrations'
    | '/$did/sandbox/$rkey/ports'
    | '/$did/sandbox/$rkey/repository'
    | '/$did/sandbox/$rkey/secrets'
    | '/$did/sandbox/$rkey/services'
    | '/$did/sandbox/$rkey/settings'
    | '/$did/sandbox/$rkey/ssh-keys'
    | '/$did/sandbox/$rkey/tailscale'
    | '/$did/sandbox/$rkey/variables'
    | '/$did/sandbox/$rkey/volumes'
    | '/$did/sandbox/$rkey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/projects'
    | '/secrets'
    | '/settings'
    | '/signin'
    | '/snapshots'
    | '/volumes'
    | '/sandbox/$id'
    | '/$did/sandbox/$rkey/files'
    | '/$did/sandbox/$rkey/integrations'
    | '/$did/sandbox/$rkey/ports'
    | '/$did/sandbox/$rkey/repository'
    | '/$did/sandbox/$rkey/secrets'
    | '/$did/sandbox/$rkey/services'
    | '/$did/sandbox/$rkey/settings'
    | '/$did/sandbox/$rkey/ssh-keys'
    | '/$did/sandbox/$rkey/tailscale'
    | '/$did/sandbox/$rkey/variables'
    | '/$did/sandbox/$rkey/volumes'
    | '/$did/sandbox/$rkey'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/projects'
    | '/secrets'
    | '/settings'
    | '/signin'
    | '/snapshots'
    | '/volumes'
    | '/sandbox/$id'
    | '/$did/sandbox/$rkey'
    | '/$did/sandbox/$rkey/files'
    | '/$did/sandbox/$rkey/integrations'
    | '/$did/sandbox/$rkey/ports'
    | '/$did/sandbox/$rkey/repository'
    | '/$did/sandbox/$rkey/secrets'
    | '/$did/sandbox/$rkey/services'
    | '/$did/sandbox/$rkey/settings'
    | '/$did/sandbox/$rkey/ssh-keys'
    | '/$did/sandbox/$rkey/tailscale'
    | '/$did/sandbox/$rkey/variables'
    | '/$did/sandbox/$rkey/volumes'
    | '/$did/sandbox/$rkey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ProjectsRoute: typeof ProjectsRoute
  SecretsRoute: typeof SecretsRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SnapshotsRoute: typeof SnapshotsRoute
  VolumesRoute: typeof VolumesRoute
  SandboxIdRoute: typeof SandboxIdRoute
  DidSandboxRkeyRoute: typeof DidSandboxRkeyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volumes': {
      id: '/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof VolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/$id': {
      id: '/sandbox/$id'
      path: '/sandbox/$id'
      fullPath: '/sandbox/$id'
      preLoaderRoute: typeof SandboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$did/sandbox/$rkey': {
      id: '/$did/sandbox/$rkey'
      path: '/$did/sandbox/$rkey'
      fullPath: '/$did/sandbox/$rkey'
      preLoaderRoute: typeof DidSandboxRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$did/sandbox/$rkey/': {
      id: '/$did/sandbox/$rkey/'
      path: '/'
      fullPath: '/$did/sandbox/$rkey/'
      preLoaderRoute: typeof DidSandboxRkeyIndexRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/volumes': {
      id: '/$did/sandbox/$rkey/volumes'
      path: '/volumes'
      fullPath: '/$did/sandbox/$rkey/volumes'
      preLoaderRoute: typeof DidSandboxRkeyVolumesRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/variables': {
      id: '/$did/sandbox/$rkey/variables'
      path: '/variables'
      fullPath: '/$did/sandbox/$rkey/variables'
      preLoaderRoute: typeof DidSandboxRkeyVariablesRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/tailscale': {
      id: '/$did/sandbox/$rkey/tailscale'
      path: '/tailscale'
      fullPath: '/$did/sandbox/$rkey/tailscale'
      preLoaderRoute: typeof DidSandboxRkeyTailscaleRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/ssh-keys': {
      id: '/$did/sandbox/$rkey/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/$did/sandbox/$rkey/ssh-keys'
      preLoaderRoute: typeof DidSandboxRkeySshKeysRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/settings': {
      id: '/$did/sandbox/$rkey/settings'
      path: '/settings'
      fullPath: '/$did/sandbox/$rkey/settings'
      preLoaderRoute: typeof DidSandboxRkeySettingsRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/services': {
      id: '/$did/sandbox/$rkey/services'
      path: '/services'
      fullPath: '/$did/sandbox/$rkey/services'
      preLoaderRoute: typeof DidSandboxRkeyServicesRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/secrets': {
      id: '/$did/sandbox/$rkey/secrets'
      path: '/secrets'
      fullPath: '/$did/sandbox/$rkey/secrets'
      preLoaderRoute: typeof DidSandboxRkeySecretsRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/repository': {
      id: '/$did/sandbox/$rkey/repository'
      path: '/repository'
      fullPath: '/$did/sandbox/$rkey/repository'
      preLoaderRoute: typeof DidSandboxRkeyRepositoryRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/ports': {
      id: '/$did/sandbox/$rkey/ports'
      path: '/ports'
      fullPath: '/$did/sandbox/$rkey/ports'
      preLoaderRoute: typeof DidSandboxRkeyPortsRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/integrations': {
      id: '/$did/sandbox/$rkey/integrations'
      path: '/integrations'
      fullPath: '/$did/sandbox/$rkey/integrations'
      preLoaderRoute: typeof DidSandboxRkeyIntegrationsRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
    '/$did/sandbox/$rkey/files': {
      id: '/$did/sandbox/$rkey/files'
      path: '/files'
      fullPath: '/$did/sandbox/$rkey/files'
      preLoaderRoute: typeof DidSandboxRkeyFilesRouteImport
      parentRoute: typeof DidSandboxRkeyRoute
    }
  }
}

interface DidSandboxRkeyRouteChildren {
  DidSandboxRkeyFilesRoute: typeof DidSandboxRkeyFilesRoute
  DidSandboxRkeyIntegrationsRoute: typeof DidSandboxRkeyIntegrationsRoute
  DidSandboxRkeyPortsRoute: typeof DidSandboxRkeyPortsRoute
  DidSandboxRkeyRepositoryRoute: typeof DidSandboxRkeyRepositoryRoute
  DidSandboxRkeySecretsRoute: typeof DidSandboxRkeySecretsRoute
  DidSandboxRkeyServicesRoute: typeof DidSandboxRkeyServicesRoute
  DidSandboxRkeySettingsRoute: typeof DidSandboxRkeySettingsRoute
  DidSandboxRkeySshKeysRoute: typeof DidSandboxRkeySshKeysRoute
  DidSandboxRkeyTailscaleRoute: typeof DidSandboxRkeyTailscaleRoute
  DidSandboxRkeyVariablesRoute: typeof DidSandboxRkeyVariablesRoute
  DidSandboxRkeyVolumesRoute: typeof DidSandboxRkeyVolumesRoute
  DidSandboxRkeyIndexRoute: typeof DidSandboxRkeyIndexRoute
}

const DidSandboxRkeyRouteChildren: DidSandboxRkeyRouteChildren = {
  DidSandboxRkeyFilesRoute: DidSandboxRkeyFilesRoute,
  DidSandboxRkeyIntegrationsRoute: DidSandboxRkeyIntegrationsRoute,
  DidSandboxRkeyPortsRoute: DidSandboxRkeyPortsRoute,
  DidSandboxRkeyRepositoryRoute: DidSandboxRkeyRepositoryRoute,
  DidSandboxRkeySecretsRoute: DidSandboxRkeySecretsRoute,
  DidSandboxRkeyServicesRoute: DidSandboxRkeyServicesRoute,
  DidSandboxRkeySettingsRoute: DidSandboxRkeySettingsRoute,
  DidSandboxRkeySshKeysRoute: DidSandboxRkeySshKeysRoute,
  DidSandboxRkeyTailscaleRoute: DidSandboxRkeyTailscaleRoute,
  DidSandboxRkeyVariablesRoute: DidSandboxRkeyVariablesRoute,
  DidSandboxRkeyVolumesRoute: DidSandboxRkeyVolumesRoute,
  DidSandboxRkeyIndexRoute: DidSandboxRkeyIndexRoute,
}

const DidSandboxRkeyRouteWithChildren = DidSandboxRkeyRoute._addFileChildren(
  DidSandboxRkeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ProjectsRoute: ProjectsRoute,
  SecretsRoute: SecretsRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SnapshotsRoute: SnapshotsRoute,
  VolumesRoute: VolumesRoute,
  SandboxIdRoute: SandboxIdRoute,
  DidSandboxRkeyRoute: DidSandboxRkeyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
