import type { Context } from "context";
import type { Server } from "lexicon";
import createSandbox from "./io/pocketenv/sandbox/createSandbox";
import deleteSandbox from "./io/pocketenv/sandbox/deleteSandbox";
import getSandbox from "./io/pocketenv/sandbox/getSandbox";
import getSandboxes from "./io/pocketenv/sandbox/getSandboxes";
import startSandbox from "./io/pocketenv/sandbox/startSandbox";
import stopSandbox from "./io/pocketenv/sandbox/stopSandbox";
import claimSandbox from "./io/pocketenv/sandbox/claimSandbox";
import getProfile from "./io/pocketenv/actor/getProfile";
import getActorSandboxes from "./io/pocketenv/actor/getActorSandboxes";
import getTerminalToken from "./io/pocketenv/actor/getTerminalToken";
import addFile from "./io/pocketenv/file/addFile";
import deleteFile from "./io/pocketenv/file/deleteFile";
import getFiles from "./io/pocketenv/file/getFiles";
import addSecret from "./io/pocketenv/secret/addSecret";
import deleteSecret from "./io/pocketenv/secret/deleteSecret";
import getSecrets from "./io/pocketenv/secret/getSecrets";
import addVolume from "./io/pocketenv/volume/addVolume";
import deleteVolume from "./io/pocketenv/volume/deleteVolume";
import getVolumes from "./io/pocketenv/volume/getVolumes";
import putPreferences from "./io/pocketenv/sandbox/putPreferences";
import getPreferences from "./io/pocketenv/sandbox/getPreferences";
import addVariable from "./io/pocketenv/variable/addVariable";
import getVariables from "./io/pocketenv/variable/getVariables";
import createIntegration from "./io/pocketenv/sandbox/createIntegration";
import getIntegrations from "./io/pocketenv/sandbox/getIntegrations";
import getSshKeys from "./io/pocketenv/sandbox/getSshKeys";
import getTailscaleAuthKey from "./io/pocketenv/sandbox/getTailscaleAuthKey";
import putSshKeys from "./io/pocketenv/sandbox/putSshKeys";
import putTailscaleAuthKey from "./io/pocketenv/sandbox/putTailscaleAuthKey";
import getFile from "./io/pocketenv/file/getFile";
import getSecret from "./io/pocketenv/secret/getSecret";
import getVariable from "./io/pocketenv/variable/getVariable";
import getVolume from "./io/pocketenv/volume/getVolume";
import deleteVariable from "./io/pocketenv/variable/deleteVariable";
import updateFile from "./io/pocketenv/file/updateFile";
import updateSecret from "./io/pocketenv/secret/updateSecret";
import updateVariable from "./io/pocketenv/variable/updateVariable";
import updateVolume from "./io/pocketenv/volume/updateVolume";
import exposePort from "./io/pocketenv/sandbox/exposePort";
import getExposedPorts from "./io/pocketenv/sandbox/getExposedPorts";
import unexposePort from "./io/pocketenv/sandbox/unexposePort";
import exposeVscode from "./io/pocketenv/sandbox/exposeVscode";
import exec from "./io/pocketenv/sandbox/exec";
import addService from "./io/pocketenv/service/addService";
import deleteService from "./io/pocketenv/service/deleteService";
import getServices from "./io/pocketenv/service/getServices";
import restartService from "./io/pocketenv/service/restartService";
import updateService from "./io/pocketenv/service/updateService";
import startService from "./io/pocketenv/service/startService";
import stopService from "./io/pocketenv/service/stopService";
import pushDirectory from "./io/pocketenv/sandbox/pushDirectory";
import pullDirectory from "./io/pocketenv/sandbox/pullDirectory";
import createBackup from "./io/pocketenv/sandbox/createBackup";
import getBackups from "./io/pocketenv/sandbox/getBackups";
import restoreBackup from "./io/pocketenv/sandbox/restoreBackup";

export default function (server: Server, ctx: Context) {
  // io.pocketenv
  getSandbox(server, ctx);
  getSandboxes(server, ctx);
  getActorSandboxes(server, ctx);
  createSandbox(server, ctx);
  deleteSandbox(server, ctx);
  startSandbox(server, ctx);
  stopSandbox(server, ctx);
  claimSandbox(server, ctx);
  getProfile(server, ctx);
  getTerminalToken(server, ctx);
  putPreferences(server, ctx);
  getPreferences(server, ctx);
  addFile(server, ctx);
  deleteFile(server, ctx);
  getFiles(server, ctx);
  addSecret(server, ctx);
  addVariable(server, ctx);
  getVariables(server, ctx);
  deleteSecret(server, ctx);
  getSecrets(server, ctx);
  addVolume(server, ctx);
  deleteVolume(server, ctx);
  getVolumes(server, ctx);
  createIntegration(server, ctx);
  getIntegrations(server, ctx);
  getSshKeys(server, ctx);
  getTailscaleAuthKey(server, ctx);
  putSshKeys(server, ctx);
  putTailscaleAuthKey(server, ctx);
  getFile(server, ctx);
  getSecret(server, ctx);
  getVariable(server, ctx);
  getVolume(server, ctx);
  deleteFile(server, ctx);
  deleteSecret(server, ctx);
  deleteVolume(server, ctx);
  deleteVariable(server, ctx);
  updateFile(server, ctx);
  updateSecret(server, ctx);
  updateVariable(server, ctx);
  updateVolume(server, ctx);
  exposePort(server, ctx);
  getExposedPorts(server, ctx);
  unexposePort(server, ctx);
  exposeVscode(server, ctx);
  exec(server, ctx);
  addService(server, ctx);
  deleteService(server, ctx);
  getServices(server, ctx);
  restartService(server, ctx);
  updateService(server, ctx);
  startService(server, ctx);
  stopService(server, ctx);
  pushDirectory(server, ctx);
  pullDirectory(server, ctx);
  createBackup(server, ctx);
  getBackups(server, ctx);
  restoreBackup(server, ctx);

  return server;
}
