export const images: Record<string, string> = {
  openclaw: "ghcr.io/pocketenv-io/daytona-openclaw:0.6.0",
  amp: "ghcr.io/pocketenv-io/daytona-amp:0.6.0",
  claude: "ghcr.io/pocketenv-io/daytona-claude:0.6.0",
  codex: "ghcr.io/pocketenv-io/daytona-codex:0.6.0",
  copilot: "ghcr.io/pocketenv-io/daytona-copilot:0.6.0",
  crush: "ghcr.io/pocketenv-io/daytona-crush:0.6.0",
  cursor: "ghcr.io/pocketenv-io/daytona-cursor:0.6.0",
  gemini: "ghcr.io/pocketenv-io/daytona-gemini:0.6.0",
  kilo: "ghcr.io/pocketenv-io/daytona-kilo:0.6.0",
  kiro: "ghcr.io/pocketenv-io/daytona-kiro:0.6.0",
  mise: "ghcr.io/pocketenv-io/daytona-mise:0.6.0",
  nix: "ghcr.io/pocketenv-io/daytona-nix:0.6.0",
  nullclaw: "ghcr.io/pocketenv-io/daytona-nullclaw:0.6.0",
  opencode: "ghcr.io/pocketenv-io/daytona-opencode:0.6.0",
  opencrust: "ghcr.io/pocketenv-io/daytona-opencrust:0.6.0",
  picoclaw: "ghcr.io/pocketenv-io/daytona-picoclaw:0.6.0",
  pkgx: "ghcr.io/pocketenv-io/daytona-pkgx:0.6.0",
  wasmer: "ghcr.io/pocketenv-io/daytona-wasmer:0.6.0",
  zeroclaw: "ghcr.io/pocketenv-io/daytona-zeroclaw:0.6.0",
};
